-- Your SQL goes here
CREATE TABLE IF NOT EXISTS chiller_xa_hvar_parameters_minutes_hist (
    unit_id int NOT NULL,
    device_code text NOT NULL,
    genuint_ui DECIMAL(10, 2) NOT NULL,
    cap_t DECIMAL(10, 2) NOT NULL,
    tot_curr DECIMAL(10, 2) NOT NULL,
    ctrl_pnt DECIMAL(10, 2) NOT NULL,
    oat DECIMAL(10, 2) NOT NULL,
    cool_ewt DECIMAL(10, 2) NOT NULL,
    cool_lwt DECIMAL(10, 2) NOT NULL,
    cond_lwt DECIMAL(10, 2) NOT NULL,
    cond_ewt DECIMAL(10, 2) NOT NULL,
    circa_an_ui DECIMAL(10, 2) NOT NULL,
    capa_t DECIMAL(10, 2) NOT NULL,
    dp_a DECIMAL(10, 2) NOT NULL,
    sp_a DECIMAL(10, 2) NOT NULL,
    econ_p_a DECIMAL(10, 2) NOT NULL,
    op_a DECIMAL(10, 2) NOT NULL,
    dop_a DECIMAL(10, 2) NOT NULL,
    curren_a DECIMAL(10, 2) NOT NULL,
    cp_tmp_a DECIMAL(10, 2) NOT NULL,
    dgt_a DECIMAL(10, 2) NOT NULL,
    eco_tp_a DECIMAL(10, 2) NOT NULL,
    sct_a DECIMAL(10, 2) NOT NULL,
    sst_a DECIMAL(10, 2) NOT NULL,
    sst_b DECIMAL(10, 2) NOT NULL,
    suct_t_a DECIMAL(10, 2) NOT NULL,
    exv_a DECIMAL(10, 2) NOT NULL,
    circb_an_ui DECIMAL(10, 2) NOT NULL,
    capb_t DECIMAL(10, 2) NOT NULL,
    dp_b DECIMAL(10, 2) NOT NULL,
    sp_b DECIMAL(10, 2) NOT NULL,
    econ_p_b DECIMAL(10, 2) NOT NULL,
    op_b DECIMAL(10, 2) NOT NULL,
    dop_b DECIMAL(10, 2) NOT NULL,
    curren_b DECIMAL(10, 2) NOT NULL,
    cp_tmp_b DECIMAL(10, 2) NOT NULL,
    dgt_b DECIMAL(10, 2) NOT NULL,
    eco_tp_b DECIMAL(10, 2) NOT NULL,
    sct_b DECIMAL(10, 2) NOT NULL,
    suct_t_b DECIMAL(10, 2) NOT NULL,
    exv_b DECIMAL(10, 2) NOT NULL,
    circc_an_ui DECIMAL(10, 2) NOT NULL,
    capc_t DECIMAL(10, 2) NOT NULL,
    dp_c DECIMAL(10, 2) NOT NULL,
    sp_c DECIMAL(10, 2) NOT NULL,
    econ_p_c DECIMAL(10, 2) NOT NULL,
    op_c DECIMAL(10, 2) NOT NULL,
    dop_c DECIMAL(10, 2) NOT NULL,
    curren_c DECIMAL(10, 2) NOT NULL,
    cp_tmp_c DECIMAL(10, 2) NOT NULL,
    dgt_c DECIMAL(10, 2) NOT NULL,
    eco_tp_c DECIMAL(10, 2) NOT NULL,
    sct_c DECIMAL(10, 2) NOT NULL,
    sst_c DECIMAL(10, 2) NOT NULL,
    suct_t_c DECIMAL(10, 2) NOT NULL,
    exv_c DECIMAL(10, 2) NOT NULL,
    record_date TIMESTAMP NOT NULL,
    PRIMARY KEY(device_code, record_date),
    CONSTRAINT chiller_telemetry_hist_fk_unit_id FOREIGN KEY (unit_id) REFERENCES units (id)
);

select create_hypertable('chiller_xa_hvar_parameters_minutes_hist', 'record_date');
