use crate::schema::chiller_xa_hvar_parameters_minutes_hist ;
use chrono::NaiveDateTime;
use serde::Serialize;

use diesel::{sql_types::{Integer, Numeric, Text, Timestamp}, Insertable, Queryable, QueryableByName};

use rust_decimal::Decimal;

#[derive(Debug, Queryable, QueryableByName, Insertable, Serialize)]
#[table_name = "chiller_xa_hvar_parameters_minutes_hist"]
pub struct ChillerXAHvarParametersMinutesHist {
    pub device_code: String,
    pub unit_id: i32,
    pub record_date: NaiveDateTime,
    pub genunit_ui: Decimal,
    pub cap_t: Decimal,
    pub tot_curr: Decimal,
    pub ctrl_pnt: Decimal,
    pub oat: Decimal,
    pub cool_ewt: Decimal,
    pub cool_lwt: Decimal,
    pub circa_an_ui: Decimal,
    pub capa_t: Decimal,
    pub dp_a: Decimal,
    pub sp_a: Decimal,
    pub econ_p_a: Decimal,
    pub op_a: Decimal,
    pub dop_a: Decimal,
    pub curren_a: Decimal,
    pub cp_tmp_a: Decimal,
    pub dgt_a: Decimal,
    pub eco_tp_a: Decimal,
    pub sct_a: Decimal,
    pub sst_a: Decimal,
    pub sst_b: Decimal,
    pub suct_t_a: Decimal,
    pub exv_a: Decimal,
    pub circb_an_ui: Decimal,
    pub capb_t: Decimal,
    pub dp_b: Decimal,
    pub sp_b: Decimal,
    pub econ_p_b: Decimal,
    pub op_b: Decimal,
    pub dop_b: Decimal,
    pub curren_b: Decimal,
    pub cp_tmp_b: Decimal,
    pub dgt_b: Decimal,
    pub eco_tp_b: Decimal,
    pub sct_b: Decimal,
    pub suct_t_b: Decimal,
    pub exv_b: Decimal,
    pub circc_an_ui: Decimal,
    pub capc_t: Decimal,
    pub dp_c: Decimal,
    pub sp_c: Decimal,
    pub econ_p_c: Decimal,
    pub op_c: Decimal,
    pub dop_c: Decimal,
    pub curren_c: Decimal,
    pub cp_tmp_c: Decimal,
    pub dgt_c: Decimal,
    pub eco_tp_c: Decimal,
    pub sct_c: Decimal,
    pub sst_c: Decimal,
    pub suct_t_c: Decimal,
    pub exv_c: Decimal,
}

#[derive(Debug, QueryableByName, Serialize)]
pub struct ChillerXAHvarParametersHistRow {
    #[diesel(sql_type = Text)]
    pub device_code: String,
    #[diesel(sql_type = Integer)]
    pub unit_id: i32,
    #[diesel(sql_type = Timestamp)]
    pub record_date: NaiveDateTime,
    #[diesel(sql_type = Numeric)]
    pub genunit_ui: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cap_t: Decimal,
    #[diesel(sql_type = Numeric)]
    pub tot_curr: Decimal,
    #[diesel(sql_type = Numeric)]
    pub ctrl_pnt: Decimal,
    #[diesel(sql_type = Numeric)]
    pub oat: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cool_ewt: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cool_lwt: Decimal,
    #[diesel(sql_type = Numeric)]
    pub circa_an_ui: Decimal,
    #[diesel(sql_type = Numeric)]
    pub capa_t: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dp_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sp_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub econ_p_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub op_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dop_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub curren_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cp_tmp_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dgt_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub eco_tp_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sct_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sst_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sst_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub suct_t_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub exv_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub circb_an_ui: Decimal,
    #[diesel(sql_type = Numeric)]
    pub capb_t: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dp_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sp_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub econ_p_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub op_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dop_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub curren_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cp_tmp_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dgt_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub eco_tp_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sct_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub suct_t_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub exv_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub circc_an_ui: Decimal,
    #[diesel(sql_type = Numeric)]
    pub capc_t: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dp_c: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sp_c: Decimal,
    #[diesel(sql_type = Numeric)]
    pub econ_p_c: Decimal,
    #[diesel(sql_type = Numeric)]
    pub op_c: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dop_c: Decimal,
    #[diesel(sql_type = Numeric)]
    pub curren_c: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cp_tmp_c: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dgt_c: Decimal,
    #[diesel(sql_type = Numeric)]
    pub eco_tp_c: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sct_c: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sst_c: Decimal,
    #[diesel(sql_type = Numeric)]
    pub suct_t_c: Decimal,
    #[diesel(sql_type = Numeric)]
    pub exv_c: Decimal,
}
