use crate::schema::chiller_hx_parameters_minutes_hist;
use chrono::NaiveDateTime;
use serde::Serialize;

use diesel::{sql_types::{Integer, Numeric, Text, Timestamp}, Insertable, Queryable, QueryableByName};

use rust_decimal::Decimal;

#[derive(Debug, Queryable, QueryableByName, Insertable, Serialize)]
#[table_name = "chiller_hx_parameters_minutes_hist"]
pub struct ChillerHXParametersMinutesHist {
    pub device_code: String,
    pub unit_id: i32,
    pub record_date: NaiveDateTime,
    pub cap_t: Decimal,
    pub dem_lim: Decimal,
    pub lag_lim: Decimal,
    pub sp: Decimal,
    pub ctrl_pnt: Decimal,
    pub capa_t: Decimal,
    pub dp_a: Decimal,
    pub sp_a: Decimal,
    pub sct_a: Decimal,
    pub sst_a: Decimal,
    pub capb_t: Decimal,
    pub dp_b: Decimal,
    pub sp_b: Decimal,
    pub sct_b: Decimal,
    pub sst_b: Decimal,
    pub cond_lwt: Decimal,
    pub cond_ewt: Decimal,
    pub cool_lwt: Decimal,
    pub cool_ewt: Decimal,
    pub cpa1_op: Decimal,
    pub cpa2_op: Decimal,
    pub dop_a1: Decimal,
    pub dop_a2: Decimal,
    pub cpa1_dgt: Decimal,
    pub cpa2_dgt: Decimal,
    pub exv_a: Decimal,
    pub hr_cp_a1: Decimal,
    pub hr_cp_a2: Decimal,
    pub cpa1_tmp: Decimal,
    pub cpa2_tmp: Decimal,
    pub cpa1_cur: Decimal,
    pub cpa2_cur: Decimal,
    pub cpb1_op: Decimal,
    pub cpb2_op: Decimal,
    pub dop_b1: Decimal,
    pub dop_b2: Decimal,
    pub cpb1_dgt: Decimal,
    pub cpb2_dgt: Decimal,
    pub exv_b: Decimal,
    pub hr_cp_b1: Decimal,
    pub hr_cp_b2: Decimal,
    pub cpb1_tmp: Decimal,
    pub cpb2_tmp: Decimal,
    pub cpb1_cur: Decimal,
    pub cpb2_cur: Decimal,
    pub cond_sp: Decimal,
}

#[derive(Debug, QueryableByName, Serialize)]
pub struct ChillerHXParametersHistRow {
    #[diesel(sql_type = Text)]
    pub device_code: String,
    #[diesel(sql_type = Integer)]
    pub unit_id: i32,
    #[diesel(sql_type = Timestamp)]
    pub record_date: NaiveDateTime,
    #[diesel(sql_type = Numeric)]
    pub cap_t: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dem_lim: Decimal,
    #[diesel(sql_type = Numeric)]
    pub lag_lim: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sp: Decimal,
    #[diesel(sql_type = Numeric)]
    pub ctrl_pnt: Decimal,
    #[diesel(sql_type = Numeric)]
    pub capa_t: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dp_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sp_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sct_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sst_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub capb_t: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dp_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sp_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sct_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub sst_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cond_lwt: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cond_ewt: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cool_lwt: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cool_ewt: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpa1_op: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpa2_op: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dop_a1: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dop_a2: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpa1_dgt: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpa2_dgt: Decimal,
    #[diesel(sql_type = Numeric)]
    pub exv_a: Decimal,
    #[diesel(sql_type = Numeric)]
    pub hr_cp_a1: Decimal,
    #[diesel(sql_type = Numeric)]
    pub hr_cp_a2: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpa1_tmp: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpa2_tmp: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpa1_cur: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpa2_cur: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpb1_op: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpb2_op: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dop_b1: Decimal,
    #[diesel(sql_type = Numeric)]
    pub dop_b2: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpb1_dgt: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpb2_dgt: Decimal,
    #[diesel(sql_type = Numeric)]
    pub exv_b: Decimal,
    #[diesel(sql_type = Numeric)]
    pub hr_cp_b1: Decimal,
    #[diesel(sql_type = Numeric)]
    pub hr_cp_b2: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpb1_tmp: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpb2_tmp: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpb1_cur: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cpb2_cur: Decimal,
    #[diesel(sql_type = Numeric)]
    pub cond_sp: Decimal,
}
